export const MOCK_WORKER = {
  user_id: "usr_w101",
  name: "Lakshmi Devi",
  role: "asha_worker",
  phone: "+919876543210",
  phc_name: "PHC Ramanthapur Hub",
  assigned_village: "Ramanthapur",
  daily_max_visits: 10,
  current_location: {
    latitude: 17.3950,
    longitude: 78.5300,
  }
};

export const MOCK_PATIENTS = [
  {
    patient_id: "pat_001",
    name: "Sunitha Rao",
    age: 26,
    gender: "female",
    village: "Ramanthapur Sector 1",
    latitude: 17.3984,
    longitude: 78.5382,
    is_pregnant: true,
    trimester: 3,
    high_risk_pregnancy: true,
    newborn_age_days: 0,
    vaccination_status: "due",
    days_overdue: 5,
    chronic_disease_flags: ["anemia", "hypertension"],
    previous_missed_visits: 1,
    visit_type: "anc_checkup",
    last_visit_days_ago: 14,
    risk_score: 85,
    risk_band: "Critical",
    assigned_worker_id: "usr_w101",
    preferred_time_window: { start: "09:30", end: "11:30" }
  },
  {
    patient_id: "pat_002",
    name: "Priyanka Reddy",
    age: 24,
    gender: "female",
    village: "Uppal Main Road",
    latitude: 17.4012,
    longitude: 78.5601,
    is_pregnant: true,
    trimester: 2,
    high_risk_pregnancy: false,
    newborn_age_days: 0,
    vaccination_status: "up_to_date",
    days_overdue: 0,
    chronic_disease_flags: [],
    previous_missed_visits: 0,
    visit_type: "anc_checkup",
    last_visit_days_ago: 30,
    risk_score: 42,
    risk_band: "Moderate",
    assigned_worker_id: "usr_w101",
    preferred_time_window: { start: "13:00", end: "16:00" }
  },
  {
    patient_id: "pat_003",
    name: "Anitha Kumar",
    age: 29,
    gender: "female",
    village: "Habsiguda Colony",
    latitude: 17.4110,
    longitude: 78.5480,
    is_pregnant: false,
    trimester: 0,
    high_risk_pregnancy: false,
    newborn_age_days: 12,
    vaccination_status: "overdue",
    days_overdue: 8,
    chronic_disease_flags: ["diabetes"],
    previous_missed_visits: 0,
    visit_type: "pnc_checkup",
    last_visit_days_ago: 10,
    risk_score: 74,
    risk_band: "High",
    assigned_worker_id: "usr_w101",
    preferred_time_window: { start: "11:30", end: "13:00" }
  },
  {
    patient_id: "pat_004",
    name: "Deepa Rani",
    age: 32,
    gender: "female",
    village: "Ramanthapur East",
    latitude: 17.3940,
    longitude: 78.5420,
    is_pregnant: false,
    trimester: 0,
    high_risk_pregnancy: false,
    newborn_age_days: 0,
    vaccination_status: "up_to_date",
    days_overdue: 0,
    chronic_disease_flags: [],
    previous_missed_visits: 0,
    visit_type: "general",
    last_visit_days_ago: 45,
    risk_score: 22,
    risk_band: "Low",
    assigned_worker_id: "usr_w101",
    preferred_time_window: { start: "14:00", end: "17:00" }
  },
  {
    patient_id: "pat_emergency_99",
    name: "Kavitha Sharma",
    age: 28,
    gender: "female",
    village: "Ramanthapur Central",
    latitude: 17.3990,
    longitude: 78.5410,
    is_pregnant: false,
    trimester: 0,
    high_risk_pregnancy: true,
    newborn_age_days: 4,
    vaccination_status: "due",
    days_overdue: 2,
    chronic_disease_flags: ["hemorrhage_risk"],
    previous_missed_visits: 0,
    visit_type: "pnc_checkup",
    last_visit_days_ago: 2,
    risk_score: 98,
    risk_band: "Critical",
    assigned_worker_id: "usr_w101",
    is_emergency: true
  }
];

export const MOCK_ROUTE_STOPS = [
  {
    sequence: 1,
    stop_id: "stp_101",
    patient_id: "pat_001",
    patient_name: "Sunitha Rao",
    village: "Ramanthapur Sector 1",
    latitude: 17.3984,
    longitude: 78.5382,
    visit_type: "anc_checkup",
    estimated_arrival: "09:40 AM",
    estimated_departure: "10:05 AM",
    travel_time_minutes: 10,
    distance_km: 2.1,
    risk_score: 85,
    risk_band: "Critical",
    status: "visited",
    is_emergency: false
  },
  {
    sequence: 2,
    stop_id: "stp_102",
    patient_id: "pat_003",
    patient_name: "Anitha Kumar",
    village: "Habsiguda Colony",
    latitude: 17.4110,
    longitude: 78.5480,
    visit_type: "pnc_checkup",
    estimated_arrival: "10:25 AM",
    estimated_departure: "10:50 AM",
    travel_time_minutes: 20,
    distance_km: 3.4,
    risk_score: 74,
    risk_band: "High",
    status: "in_progress",
    is_emergency: false
  },
  {
    sequence: 3,
    stop_id: "stp_103",
    patient_id: "pat_002",
    patient_name: "Priyanka Reddy",
    village: "Uppal Main Road",
    latitude: 17.4012,
    longitude: 78.5601,
    visit_type: "anc_checkup",
    estimated_arrival: "11:15 AM",
    estimated_departure: "11:35 AM",
    travel_time_minutes: 25,
    distance_km: 4.2,
    risk_score: 42,
    risk_band: "Moderate",
    status: "scheduled",
    is_emergency: false
  },
  {
    sequence: 4,
    stop_id: "stp_104",
    patient_id: "pat_004",
    patient_name: "Deepa Rani",
    village: "Ramanthapur East",
    latitude: 17.3940,
    longitude: 78.5420,
    visit_type: "general",
    estimated_arrival: "12:00 PM",
    estimated_departure: "12:15 PM",
    travel_time_minutes: 15,
    distance_km: 2.8,
    risk_score: 22,
    risk_band: "Low",
    status: "scheduled",
    is_emergency: false
  }
];

export const MOCK_SUPERVISOR_KPIS = {
  total_patients: 52,
  critical_risk_patients: 6,
  high_risk_patients: 14,
  moderate_risk_patients: 20,
  low_risk_patients: 12,
  scheduled_visits_today: 18,
  completed_visits_today: 14,
  missed_visits_today: 2,
  emergencies_today: 2,
  route_compliance_rate: 91.5
};

export const MOCK_AI_EXPLANATIONS = {
  "pat_001": "Sunitha Rao is prioritized as **Critical (Score: 85)** because she is in her 3rd trimester of a high-risk pregnancy with an overdue ANC checkup (5 days past due) and flagged anemia. Immediate blood pressure and hemoglobin monitoring is required.",
  "pat_003": "Anitha Kumar is scored as **High Urgency (Score: 74)** due to a 12-day-old newborn with an overdue immunization visit (8 days past due) and maternal diabetes history.",
  "pat_emergency_99": "Kavitha Sharma is classified as an **EMERGENCY (Score: 98)** due to reported severe postpartum hemorrhage 4 days post-delivery. OR-Tools solver inserted her as Priority 1 and re-routed Lakshmi Devi immediately."
};
